### PR TITLE
Staging dd

### PR DESCRIPTION
**Pull request by speelen**
Contact info landline parameter set to identifier for KLC and CIBER DDs. tam_use_of_use_3 answer option (KCL) corrected.

### CODE REVIEW

**Comment by afolarin** [comment]
Looks good to me. Do we expect some additional changes soon for VUmc -- if so let's get all our changes continue to add to the staging-dd #4 once we're ready we can merge, release and move to prod

**Comment by speelen** [comment]
I do not know. As you probably saw, I suggested for some change requests that they discuss this with the other MDD sites. I do not know whether this is planned.

**Comment by afolarin** [comment]
ok -- it's only the KCL MDD DD that's changed (these have come from prod) so we can probably just merge .

**Comment by speelen** [comment]
Yes you can

**Pull request merged**
