### PR TITLE
Study included fields added for VUmc. For all DDs hidden timestamp fi…

### PR DESCRIPTION
**Pull request by speelen**
…eld added.

### CODE REVIEW

**Comment by afolarin** [comment]
another option would be to use `@READONLY` so the date is visible to people but not modifiable, might be more useful than `@HIDDEN`

``
@READONLY | Makes the field read-only (i.e., disabled) on the survey page, the data entry form, and in the REDCap mobile app so that its value cannot be changed
```

**Comment by afolarin** [comment]
Otherwise looks good to me.

**Comment by speelen** [comment]
Should be no problem to make the timestamp fields @READONLY instead of @HIDDEN, but should the timestamp be visible in surveys? So I could set either @NOW@READONLY@HIDDEN-SURVEY or @NOW@READONLY

**Comment by afolarin** [comment]
`@NOW @READONLY @HIDDEN-SURVEY` should work, agree, no need for this to appear on surveys. But people reviewing them via the REDCap UI should be able to see but not change this.

**Comment by speelen** [comment]
OK I will then create @NOW @READONLY on the forms and not on the surveys. What is the easiest way to find out which REDCap forms are also send as surveys?

**Comment by speelen** [comment]
I have extracted the instruments for which a survey is set up from REDCap production. I noticed however that this is not always consistent between sites. For now I assume that if an instrument is indicated as a survey that for all these instruments in all studies NO timestamp will be added. The alternative is that this is done per study, based on the survey list in REDCap.

**Comment by speelen** [comment]
So you also want to have the timestamp field (hidden) present for the forms that are send out as a survey? Removing them later on will then not be possible anymore. But I guess this is not an issue since the field is hidden anyway.

**Comment by afolarin** [comment]
> So you also want to have the timestamp field (hidden) present for the forms that are send out as a survey? Removing them later on will then not be possible anymore. But I guess this is not an issue since the field is hidden anyway.

The Surveys already come with a "hidden" timestamp, in anycase we can extract one. So i guess only the Forms need one in a strict sense.

**Comment by speelen** [comment]
OK. I have now created a PR where only the non-survey forms have a @NOW @READONLY timestamp.

**Comment by afolarin** [comment]
There's a slight consequence of the `@NOW` field as it tries to update the first time a form which was created before this change is opened - i.e. it will try to set the value of the hidden time field to current date-time which will be inaccurate. Once it is saved however this will not ask for it again, so this should work fine for prospective data but there's nothing we can really do for retrospective data, I'll log this PR as the time forward of which these individual form timestamps can be used.
 
save message shown to users when the timestamp field is not set` this will be shown as long as the field is not set, once set the first time the form is saved it won't be shown again.
image


`@NOW` docs:
image

**Pull request merged**
